### ISSUE TITLE
Fails to build!

### ISSUE THREAD

**Issue by ghost** [jbreeden/mruby-zlib#3]
I get this error when my build fails `mruby-zlib/src/mruby_ZLib_macro_constants.o`

**Comment by jbreeden** [comment]
Could you post the full error message?

**Comment by ghost** [comment]
Upon further inspection I think it's possible that it may be that mruby-zlib has and incompatibility with mruby-require for some reason. The error is as follows: `Don't know how to build task '../mruby/build/host/mrbgems/mruby-zlib/src/mruby_z_stream.o' (see --tasks)`
`../mruby-require/mrbgem.rake:22:in block in print_build_summary'`
`/mruby-require/mrbgem.rake:20:in print_build_summary'`
...
`Tasks: TOP => /home/mav7/Documents/projects/mruby/build/host/lib/mruby-zlib.so`
I'm going to open up the issue with them instead.

**Comment by jbreeden** [comment]
I'd bet on the issue being with mruby-zlib if anything. I haven't used or maintained this thing in a long time. But, maybe you're right. Good luck!

**Comment by ghost** [comment]
I tried mruby-zlib with another mruby-require fork, and it built just fine. I noticed some warnings come up while building, so I'm working on a fix for that on my fork of mruby-zlib. I may have a PR for you later after I'm done testing. I hope it helps!
